"""
      🧩 Problem 1 — Log Analysis (Core Automation Skill)
Problem Statement

You are given a list of log lines generated by a backend service.

Each log line is in the format:

<TIMESTAMP> <LEVEL> <SERVICE> <MESSAGE>


Example:

2026-01-28T10:01:12 ERROR auth User login failed

Task

Write a function analyze_logs(logs: list[str]) -> dict that returns a summary with:

Count of log levels (INFO, WARN, ERROR)

List of services that generated at least one ERROR

Total number of log lines

Input Example
logs = [
    "2026-01-28T10:01:10 INFO auth User login successful",
    "2026-01-28T10:01:12 ERROR auth User login failed",
    "2026-01-28T10:02:01 WARN payment Payment delayed",
    "2026-01-28T10:02:05 ERROR payment Payment failed",
    "2026-01-28T10:03:00 INFO auth Logout successful"
]

Expected Output
{
    "level_count": {
        "INFO": 2,
        "WARN": 1,
        "ERROR": 2
    },
    "error_services": ["auth", "payment"],
    "total_logs": 5
}

Constraints

Order of error_services does not matter

Logs may contain extra spaces in messages

Assume logs are well-formed
"""

from collections import defaultdict
from typing import Iterable


def generator_log_file(log_file_name: str) -> Iterable:
    """
    Generator function for logging file
    :param log_file_name:
    """
    with open(log_file_name, "r") as log_file:
        for line in log_file:
            yield line


def process_log_file(log_file_name: str) -> dict:
    level_count = defaultdict(int)
    error_services = set()
    total_logs = 0
    for line in generator_log_file(log_file_name):
        parts = line.split()
        level = parts[1]
        service = parts[2]

        level_count[level] += 1
        if level == "ERROR":
            error_services.add(service)
        total_logs +=1

    return {
        "level_count": dict(level_count),
        "error_services": list(error_services),
        "total_logs": total_logs
    }
